/**
 * @file sensor_panel.h
 * @brief IMU sensor data display (gyro, accel)
 */

#ifndef SENSOR_PANEL_H
#define SENSOR_PANEL_H

#include "gui/panel.h"

/**
 * @class SensorPanel
 * @brief UI panel displaying simulated IMU sensor measurements
 *
 * Shows:
 * - Gyroscope readings (rad/s) in body frame
 * - Accelerometer readings (m/s²) in body frame
 * - Sensor health/status indicators (future)
 *
 * Data is generated by SensorSimulatorModule and displayed
 * as numeric values or gauges.
 */
class SensorPanel : public Panel {
public:
    const char* name() const override { return "Sensor Suite"; }
    void draw(SimulationState& state, Camera& camera) override;
};

#endif // SENSOR_PANEL_H
